<img src="https://raw.githubusercontent.com/saulocatharino/assistente_virtual/master/logobeetlabs.png" width=600>
<br><br>

<h1><b>MENTORIA PERSONALIZADA</b></h1><br>


---


<br>
<h4><b>INTRODUÇÃO AO SCIKIT-LEARN</b></h4>
<br>
Uma das mais conhecidas bibliotecas por obter um pacote que fornece versões eficientes de um grande número de algoritmos comuns.
<br><br>
O Scikit-Learn é caracterizado por ser simples e por possuir uma <a href ='https://scikit-learn.org/stable/' target='_blank'>documentação</a> online completa bem compreensível.
<br><br>


---

<br>


## **CLASSIFICAÇÃO** ##

Aprendizado supervisionado utilizado para identificar a qual categoria um objeto pertence.
<br><br>
<b>Aplicações:</b><br> Detecção de SPAM, Reconhecimento de Imagens, Reconhecimento de Pessoas, entre outras.


<br><br>
<img src='https://raw.githubusercontent.com/saulocatharino/Imers-oPython/main/ML%20-%200.png' width=600>
<br>
<img src='https://raw.githubusercontent.com/saulocatharino/Imers-oPython/main/ML%20-%201.png' width=600>
<br>
<img src='https://raw.githubusercontent.com/saulocatharino/Imers-oPython/main/ML%20-%202.png' width=600>
<br>
<img src='https://raw.githubusercontent.com/saulocatharino/Imers-oPython/main/ML%20-%203.png' width=600>
<br>
<img src='https://raw.githubusercontent.com/saulocatharino/Imers-oPython/main/ML%20-%204.png' width=600>
<br>
<img src='hhttps://raw.githubusercontent.com/saulocatharino/Imers-oPython/main/ML%20-%206.png' width=600>
<br>
<img src='https://raw.githubusercontent.com/saulocatharino/Imers-oPython/main/ML%20-%207.png' width=600>
<br>
<img src='https://raw.githubusercontent.com/saulocatharino/Imers-oPython/main/ML%20-%208.png' width=600>

<br>
<img src='https://raw.githubusercontent.com/saulocatharino/Imers-oPython/main/ML%20-%209.png' width=600>

## **REGRESSÃO**##

Aprendizado supervisionado utilizado para prever um atributo de valor contínuo associado a um objeto.
<br>
<b>Aplicações:</b><br>
Aplicações: Resposta a medicamentos, Preços de ações, Detecção de anomalias, entre outras.


<br>
<img src='https://drive.google.com/uc?export=view&id=13tjCtlqSxIDvq4qc01DiugvJOJOIaxew' width=600>
<br>
<img src='https://drive.google.com/uc?export=view&id=1GOEHVIo6PiLg3tsLIQm9mK21qpEfnCI0' width=600>
<br>
<img src='https://drive.google.com/uc?export=view&id=19vLOf_cEIbCWTskCMDc3MPTCHsy41qKr' width=600>

## **CLUSTER** ##

Agrupamento automático de objetos semelhantes em conjuntos.<br>
<b>Aplicações:</b><br>
Segmentação de clientes, resultados de experimentos de agrupamento, segmentar cores, entre outras.

<br>
<img src='https://drive.google.com/uc?export=view&id=10yIbL3LLa5bgRRWZNapSbKfg4xbRmyqn' width=600>

## **E ESTES DADOS?** ##



<img src='https://raw.githubusercontent.com/saulocatharino/Imers-oPython/main/ML%20-%2015.png' width=600>


## **QUAL ALGORITMO DEVO USAR?** ##


<img src='https://raw.githubusercontent.com/saulocatharino/Imers-oPython/main/ML%20-%2016.png' width=1000>


## **CLASSIFICAÇÃO PRÁTICA** ##

In [ ]:
from sklearn.datasets import load_iris

# Aquisição do dataset para testes contendo 3 classes de flores.
iris = load_iris()


# Verifica todas as 'keys' dentro do dataset
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
# Cria string contendo descrição do dataset
desc = iris['DESCR']

# Cria array contendo os nomes dos parâmetros, equivalente ao cabeçalho do CSV
head = iris['feature_names']

# Cria array contendo os nomes das classes de flores
label = iris['target_names']

# Cria array para treinamento de modelo contendo os valores dos 4 features para cada uma das 150 flores cadastradas
X = iris['data']

# Cria array para treinamento de modelo contendo as classes  em formato numeral, de cada uma das 150 flores cadastradas.
y = iris['target']


In [ ]:
print(desc)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [ ]:
print(head)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


<img src='https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Machine+Learning+R/iris-machinelearning.png' width=500><br>

<img src='https://python-course.eu/images/machine-learning/sepals_and_petals_600w.webp' width=500><br>

<img src='https://miro.medium.com/max/1400/1*2vTEJYgA9TnWPM81fBz7tw.png' width=500>

In [ ]:
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
print(label)

['setosa' 'versicolor' 'virginica']


In [ ]:
print(type(X))
print(type(y))
print(type(label))
print(type(desc))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'str'>


In [ ]:
print(len(X))
print(len(y))
print(len(label))
print(len(names))

150
150
3
4


In [ ]:
# Exibe a primeira flor cadastrada no banco de dados, no caso o index é o ZERO (0).

# Em 'X' temos as medidas da flor e em 'Y' qual flor é relativas às medidas 

print(X[0])
print(y[0])
classe_id = y[0]
print(label[classe_id])


[5.1 3.5 1.4 0.2]
0
setosa


<h4><b>TREINAMENTO DE MODELO</b></h4>

In [ ]:
# Importando algoritmo para classificação
from sklearn.neighbors import KNeighborsClassifier

# Criando modelo, classificando 1 vizinho como parâmetro
model = KNeighborsClassifier(n_neighbors=1)

# Treinando modelo com os valores dos atributos e as classes
model.fit(X, y);

In [ ]:
# Selecionamos um index para adquirir uma flor do dataset e ajustamos o formato da array para predição.
flor_desconhecida = [[6.8,2.1,4.8,1.4]]

# Exibe cada atributo e seu respectivo valor
for e in range(0,len(head)):
  print(head[e],flor_desconhecida[0][e])


print("-"*20)
print(flor_desconhecida)

sepal length (cm) 6.8
sepal width (cm) 2.1
petal length (cm) 4.8
petal width (cm) 1.4
--------------------
[[6.8, 2.1, 4.8, 1.4]]


<h4><b>PREDIÇÃO</b></h4>

In [ ]:
# Realiza a predição nas características encontradas
resultado = model.predict(flor_desconhecida)

# Exibe o label e a classe resultante da classificação
print("Classe: {}, Label: {}".format(resultado, label[resultado]))

Classe: [1], Label: ['versicolor']


In [ ]:
# Importa módulo para medir a precisão da classificação
from sklearn.metrics import accuracy_score

# Adquire todos os resultados da predição de todo o dataset em X
y_predicted = model.predict(X)

# Compara o resultado da predição 'y_predicted' em relação ao verdadeiro 'y'
acc = accuracy_score(y, y_predicted) * 100

print("Precisão do modelo: {}%".format(acc))

Precisão do modelo: 100.0%
